### ISSUE TITLE
Test library(urbnthemes) with geom_sf()

### ISSUE THREAD

**Issue by awunderground** [UrbanInstitute/urbnthemes#25]

**Comment by sstrochak** [comment]
There are a few things we need to do to support `geom_sf()`. I am not quite sure the default colors operate the way they should. Also, every map made with `geom_sf()` needs the argument `coord_sf(datum = NA)` to get rid of gridlines. I am not sure how taking off the gridlines gets implemented, or if the right move is to make the default grid lines close to the Urban style. Right now, they show up black when you add `theme_urbn_map()`, but grey and white with the `ggplot2` defaults. 

Example of current look with `theme_urbn_map()`:

![screen shot 2019-02-20 at 7 46 02 pm](https://user-images.githubusercontent.com/30666893/53135164-35521500-3548-11e9-83a9-a7b96dbc476a.png)

**Comment by awunderground** [comment]
@sstrochak What do we need to do to resolve this with the new `ggplot2`?
