### ISSUE TITLE
ggplot2 version installation issue

### ISSUE THREAD

**Issue by khueyama** [UrbanInstitute/urbnthemes#29]
Interesting error courtesy of Ajjit, who is running Microsoft R Open 3.4.3. Since the default MRAN repo takes a snapshot of packages on release date (2017-11-30 in this case), ggplot2 3.0.0 isn't available. Just confirmed on my own MRO distribution that if ggplot2 v2.x.x is present, it won't update to 3.0.0 and if ggplot2 isn't installed, it'll install v2.x.x (and neither case presents a warning). 

I think the fix for now is to use `packageVersion` on load and return an error.

**Comment by awunderground** [comment]
Kyle, 

Thank you for the clear diagnostic. Are you comfortable/have the time to fix this?

Best,
Aaron
